networks:
  dev:
    driver: bridge

services:
  main-app:
    container_name: app
    build:
      context: ..
      dockerfile: Dockerfile

    environment:
      KAFKA_URL: ${KAFKA_URL:?}

    ports:
      - ${API_PORT:?}:8000

    env_file:
      - ../.env

    volumes:
      - ../app/:/app/
      - ../migrations/:/migrations/
    networks:
      - dev

    depends_on:
      kafka:
        condition: service_healthy

    command: "uvicorn --factory application.api.main:create_app --timeout-graceful-shutdown 2 --host ${API_HOST:?} --port ${API_PORT:?} --reload"
