networks:
  dev:
    driver: bridge

include:
  - mariadb.yaml
  - redis.yaml

services:
  main-app:
    container_name: app
    build:
      context: ..
      dockerfile: Dockerfile

    ports:
      - ${API_PORT:?}:8000

    env_file:
      - ../.env

    volumes:
      - ..:/app
    networks:
      - dev

    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

    command: "uvicorn --factory app.application.api.main:create_app --timeout-graceful-shutdown 2 --host ${API_HOST:?} --port ${API_PORT:?} --reload"
