networks:
  dev:

services:
  main-app:
    container_name: app
    build:
      context: ..
      dockerfile: Dockerfile

    ports:
      - ${API_PORT:?}:8000

    env_file:
      - ../.env

    volumes:
      - ../app/:/app/
      - ../migrations/:/migrations/
    networks:
      dev:

    command: "uvicorn --factory application.api.main:create_app --timeout-graceful-shutdown 2 --host ${API_HOST:?} --port ${API_PORT:?} --reload"
