networks:
  dev:
    driver: bridge

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - dev  # Сетевые настройки должны быть здесь

  celery_worker:
    container_name: celery_worker
    build: ..
    command: celery -A infra.celery.celery_worker worker --pool=solo --loglevel=info
    volumes:
      - ../app/:/app/
    depends_on:
      - redis
    networks:
      - dev

  flower:
    container_name: flower
    build: ..
    command: celery -A infra.celery.celery_worker flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker
    networks:
      - dev