networks:
  dev:
    driver: bridge

include:
  - redis.yaml

services:
  celery_worker:
    container_name: celery_worker
    build: ..
    command: celery -A app.infra.celery_worker worker --pool=solo --loglevel=info
    volumes:
      - ../app:/src/app
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - dev
    env_file:
      - ../.env

  celery_beat:
    container_name: celery_beat
    build: ..
    command: celery -A app.infra.celery_worker beat --loglevel=info
    volumes:
      - ../app:/src/app
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - dev
    env_file:
      - ../.env

  flower:
    container_name: flower
    build: ..
    command: celery -A app.infra.celery_worker flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker
    networks:
      - dev
    env_file:
      - ../.env
