"""add_m2m_table_proxy_keys.

Revision ID: 0151fc7b1ee7
Revises: d6f07f6b72a8
Create Date: 2024-11-16 07:15:33.089976

"""
from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = '0151fc7b1ee7'
down_revision: Union[str, None] = 'd6f07f6b72a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'proxy_keys',
        sa.Column('proxy_id', sa.Integer(), nullable=False),
        sa.Column('key_id', sa.Integer(), nullable=False),
        sa.Column('extra_data', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['key_id'], ['api_credential.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['proxy_id'], ['proxy.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('proxy_id', 'key_id'),
    )
    op.drop_index('api_key', table_name='abusive_exp_keys')
    op.drop_table('abusive_exp_keys')
    op.drop_index('api_key', table_name='virus_total_keys')
    op.drop_table('virus_total_keys')
    op.drop_table('proxies')
    op.add_column('result', sa.Column('complete_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column(
        'result', 'virus_total',
        existing_type=mysql.TINYINT(display_width=1),
        type_=mysql.ENUM('GOOD', 'FAIL', 'WAITING', 'EMPTY'),
        nullable=False,
    )
    op.alter_column(
        'result', 'abusive_experience',
        existing_type=mysql.TINYINT(display_width=1),
        type_=mysql.ENUM('GOOD', 'FAIL', 'WAITING', 'EMPTY'),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'result', 'abusive_experience',
        existing_type=mysql.ENUM('GOOD', 'FAIL', 'WAITING', 'EMPTY'),
        type_=mysql.TINYINT(display_width=1),
        nullable=True,
    )
    op.alter_column(
        'result', 'virus_total',
        existing_type=mysql.ENUM('GOOD', 'FAIL', 'WAITING', 'EMPTY'),
        type_=mysql.TINYINT(display_width=1),
        nullable=True,
    )
    op.drop_column('result', 'complete_date')
    op.create_table(
        'proxies',
        sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column('url', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('username', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
        sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB',
    )
    op.create_table(
        'virus_total_keys',
        sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column('api_key', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('is_valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.Column('daily_limit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.Column('used_limit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
        sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB',
    )
    op.create_index('api_key', 'virus_total_keys', ['api_key'], unique=True)
    op.create_table(
        'abusive_exp_keys',
        sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column('api_key', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('is_valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.Column('daily_limit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.Column('used_limit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
        sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
        sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB',
    )
    op.create_index('api_key', 'abusive_exp_keys', ['api_key'], unique=True)
    op.drop_table('proxy_keys')
    # ### end Alembic commands ###
