"""add_credentials_models.

Revision ID: 093d31bd87d3
Revises: b835ec808d6a
Create Date: 2024-10-17 13:08:30.822698

"""
from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '093d31bd87d3'
down_revision: Union[str, None] = 'b835ec808d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'abusive_exp_keys',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('api_key', sa.String(), nullable=False),
        sa.Column('is_valid', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('api_key'),
    )
    op.create_table(
        'virus_total_keys',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('api_key', sa.String(), nullable=False),
        sa.Column('is_valid', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('api_key'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virus_total_keys')
    op.drop_table('abusive_exp_keys')
    # ### end Alembic commands ###
