"""Initial.

Revision ID: 523dc3076f9b
Revises:
Create Date: 2024-10-17 09:03:18.323653

"""
from typing import (
    Sequence,
    Union,
)


# revision identifiers, used by Alembic.
revision: str = '523dc3076f9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
