"""make_link_url_unique.

Revision ID: b835ec808d6a
Revises: 523dc3076f9b
Create Date: 2024-10-17 09:46:19.506134

"""
from typing import (
    Sequence,
    Union,
)

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b835ec808d6a'
down_revision: Union[str, None] = '523dc3076f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'link', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'link', type_='unique')
    # ### end Alembic commands ###
