"""update_api_keys_models.

Revision ID: d27de182a2ca
Revises: 093d31bd87d3
Create Date: 2024-10-19 16:43:59.882890

"""
from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd27de182a2ca'
down_revision: Union[str, None] = '093d31bd87d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abusive_exp_keys', sa.Column('daily_limit', sa.Integer(), nullable=False))
    op.add_column('abusive_exp_keys', sa.Column('used_limit', sa.Integer(), nullable=False))
    op.add_column('virus_total_keys', sa.Column('daily_limit', sa.Integer(), nullable=False))
    op.add_column('virus_total_keys', sa.Column('used_limit', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virus_total_keys', 'used_limit')
    op.drop_column('virus_total_keys', 'daily_limit')
    op.drop_column('abusive_exp_keys', 'used_limit')
    op.drop_column('abusive_exp_keys', 'daily_limit')
    # ### end Alembic commands ###
