"""initial_revision.

Revision ID: fc3b98fa8ba4
Revises:
Create Date: 2025-08-30 10:45:29.315161

"""
from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = 'fc3b98fa8ba4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'api_credential',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('api_key', sa.String(length=255), nullable=False),
        sa.Column('is_valid', sa.Boolean(), nullable=False),
        sa.Column('daily_limit', sa.Integer(), nullable=False),
        sa.Column('used_limit', sa.Integer(), nullable=False),
        sa.Column('source', mysql.ENUM('VIRUS_TOTAL', 'ABUSIVE_EXPERIENCE'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('api_key'),
    )
    op.create_table(
        'link',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('url', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url'),
    )
    op.create_table(
        'proxy',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('url', sa.String(length=255), nullable=False),
        sa.Column('username', sa.String(length=255), nullable=True),
        sa.Column('password', sa.String(length=255), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'proxy_keys',
        sa.Column('proxy_id', sa.BigInteger(), nullable=False),
        sa.Column('key_id', sa.BigInteger(), nullable=False),
        sa.Column('extra_data', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['key_id'], ['api_credential.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['proxy_id'], ['proxy.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('proxy_id', 'key_id'),
    )
    op.create_table(
        'result',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('virus_total', mysql.ENUM('GOOD', 'FAIL', 'WAITING', 'EMPTY'), nullable=False),
        sa.Column('abusive_experience', mysql.ENUM('GOOD', 'FAIL', 'WAITING', 'EMPTY'), nullable=False),
        sa.Column('link_id', sa.BigInteger(), nullable=False),
        sa.Column('complete_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['link_id'], ['link.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('link_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('proxy_keys')
    op.drop_table('proxy')
    op.drop_table('link')
    op.drop_table('api_credential')
    # ### end Alembic commands ###
